### ISSUE TITLE
redis-sentinel pod access is needed by predis

### ISSUE THREAD

**Issue by ghost** [CommercialTribe/kube-redis#10]
To use predis (PHP Redis Client) and maybe other clients with kube-redis, the clients need to contact the redis-sentinel to get information about masters and clients. To get this to work, the service would need to be expanded or another service needs to be implemented:

```
apiVersion: v1
kind: Service
metadata:
  name: redis-nodes
  labels:
    service: redis
spec:
  ports:
    - port: 6379
      name: redis
    - port: 26379
      name: redis-sentinel
  selector:
    name: redis-node
```
